[shell]
font_family = "Inter"
time_format = "{:%H:%M:%S}"
date_format = "%a, %d %b"

launch_apps_as_systemd_services = true

clipboard_enabled = true
clipboard_history_max_entries = 50

button_borders = true
input_borders = true
popup_borders = true
popup_shadows = true
corner_radius_scale = 1.25

[shell.screen_corners]
enabled = true
size = 18

[shell.animation]
enabled = true
speed = 1.15

[shell.shadow]
direction = "down"
alpha = 0.55

[shell.panel]
transparency_mode = "glass"

borders = true
shadow = true

list_item_background = true

launcher_placement = "floating"
launcher_position = "center"

clipboard_placement = "floating"
clipboard_position = "center"

control_center_placement = "attached"
wallpaper_placement = "attached"
session_placement = "attached"

floating_offset = 10

[location]
auto_locate = false
address = "São Paulo, SP, Brazil"
