[wallpaper]
enabled = true
fill_mode = "crop"
directory = "/home/vinicius/dotfiles/assets/wallpapers/"

transition = ["fade", "wipe", "disc", "zoom"]

edge_smoothness = 0.35
transition_duration = 900
transition_on_startup = true

[wallpaper.automation]
enabled = false
recursive = true
order = "random"
