[osd]
position = "top_center"
orientation = "horizontal"
position_vertical = "top_center"

scale = 1.0
border = true
background_opacity = 0.82
offset_x = 20
offset_y = 14

[osd.kinds]
volume = true
volume_output = true
volume_input = true
brightness = true
wifi = true
bluetooth = true
power_profile = true
caffeine = true
nightlight = true
dnd = true
lock_keys = true
keyboard_layout = true
privacy = true
