[theme.templates]
enable_builtin_templates = true
enable_community_templates = true

builtin_ids = [
  "ghostty",
  "gtk3",
  "gtk4",
  "qt",
  "starship"
]

community_ids = [
  "neovim",
  "obsidian"
]

