[theme.templates]
enable_builtin_templates = true
enable_community_templates = true

builtin_ids = ["ghostty", "gtk3", "gtk4", "qt", "starship"]

community_ids = [
  "neovim",
  "obsidian",
  "opencode",
  "libreoffice",
  "fastfetch",
  "obs",
]

[theme.templates.user.superfile]
input_path = "/home/vinicius/dotfiles/noctalia/templates/superfile.toml"
output_path = "$XDG_CONFIG_HOME/superfile/theme/noctalia.toml"
