"$schema" = "https://starship.rs/config-schema.json"

palette = "noctalia"

add_newline = true

scan_timeout = 30
command_timeout = 500

format = """
[╭─](fg:yellow)\
[](fg:yellow)\
$username\
[](fg:yellow bg:blue)\
$directory\
[](fg:blue bg:mauve)\
$git_branch\
$git_status\
[](fg:mauve bg:red)\
$c\
$cpp\
$golang\
$rust\
$nodejs\
$bun\
$java\
$nim\
[](fg:red bg:surface2)\
$docker_context\
[](fg:surface2)\
$cmd_duration\
$nix_shell\
$direnv\
$hostname\
$line_break\
[╰─](fg:yellow)\
$character
"""

[character]
success_symbol = "[❯](green)"
error_symbol = "[❯](red)"
vimcmd_symbol = "[❮](lavender)"

[username]
show_always = true
style_user = "bg:yellow fg:base bold"
style_root = "bg:yellow fg:base bold"
format = "[  ]($style)"

[directory]
style = "bg:blue fg:base"
format = "[ 󰉋  $path ]($style)"
truncation_length = 3
truncate_to_repo = false
read_only = " 󰌾"
read_only_style = "bg:blue fg:red"

[git_branch]
symbol = " "
style = "bg:mauve fg:base"
format = "[ $symbol$branch ]($style)"

[git_status]
style = "bg:mauve fg:base"
format = "[$all_status$ahead_behind ]($style)"
conflicted = " "
ahead = " ${count} "
behind = " ${count} "
diverged = "󰹹  ${ahead_count}  ${behind_count} "
untracked = "?${count} "
stashed = "󰏗 ${count} "
modified = "!${count} "
staged = "+${count} "
renamed = "»${count} "
deleted = "󰆴 ${count} "

[nodejs]
symbol = " "
style = "bg:red fg:base"
format = "[ $symbol$version ]($style)"

[bun]
symbol = " "
style = "bg:red fg:base"
format = "[ $symbol$version ]($style)"

[golang]
symbol = " "
style = "bg:red fg:base"
format = "[ $symbol$version ]($style)"

[rust]
symbol = " "
style = "bg:red fg:base"
format = "[ $symbol$version ]($style)"

[c]
symbol = " "
style = "bg:red fg:base"
format = "[ $symbol$version ]($style)"

[cpp]
symbol = " "
style = "bg:red fg:base"
format = "[ $symbol$version ]($style)"

[java]
symbol = " "
style = "bg:red fg:base"
format = "[ $symbol$version ]($style)"

[nim]
symbol = "󰆥 "
style = "bg:red fg:base"
format = "[ $symbol$version ]($style)"

[docker_context]
symbol = " "
style = "bg:surface2 fg:text"
format = "[ $symbol$context ]($style)"

[cmd_duration]
min_time = 2000
show_milliseconds = false
style = "fg:subtext0"
format = " [󱎫 $duration]($style)"

[nix_shell]
symbol = " "
style = "fg:blue"
format = " [$symbol$state( \\($name\\))]($style)"

[direnv]
disabled = false
symbol = " "
style = "fg:subtext0"
format = " [$symbol]($style)"

[hostname]
ssh_only = true
ssh_symbol = " "
style = "fg:red"
format = " [$ssh_symbol$hostname]($style)"

[jobs]
disabled = true
symbol = " "
number_threshold = 1
symbol_threshold = 1
style = "fg:subtext0"
format = " [$symbol$number]($style)"

[status]
disabled = true
symbol = " "
success_symbol = ""
style = "fg:red"
format = " [$symbol$status]($style)"

[time]
disabled = true
time_format = "%H:%M"
style = "bg:surface0 fg:text"
format = "[  $time ]($style)"

[palettes.noctalia]
blue = "#efb5dd"
red = "#ffb4ab"
green = "#c1c2f7"
yellow = "#c6c4dc"
cyan = "#c6c4dc"
magenta = "#c1c2f7"
white = "#e5e1e6"
black = "#46464f"
rosewater = "#c6c4dc"
flamingo = "#ffb4ab"
pink = "#c1c2f7"
mauve = "#c1c2f7"
maroon = "#ffb4ab"
peach = "#c6c4dc"
teal = "#c6c4dc"
sky = "#c6c4dc"
sapphire = "#efb5dd"
lavender = "#c1c2f7"
text = "#e5e1e6"
subtext1 = "#e5e1e6"
subtext0 = "#918f99"
overlay2 = "#918f99"
overlay1 = "#918f99"
overlay0 = "#46464f"
surface2 = "#46464f"
surface1 = "#46464f"
surface0 = "#131316"
base = "#131316"
mantle = "#131316"
crust = "#131316"
