[config]
reload_apps = false

[templates.swaync]
input_path = "~/dotfiles/matugen/templates/swaync.css"
output_path = "~/.config/swaync/style.css"

[templates.waybar]
input_path = "~/dotfiles/matugen/templates/waybar.css"
output_path = "~/.config/waybar/style.css"

[templates.rofi]
input_path = "~/dotfiles/matugen/templates/rofi.rasi"
output_path = "~/.config/rofi/theme.rasi"

[templates.nwg-bar]
input_path = "~/dotfiles/matugen/templates/nwg-bar.css"
output_path = "~/.config/nwg-bar/style.css"

[templates.orbit-theme]
input_path = "~/dotfiles/matugen/templates/orbit-theme.toml"
output_path = "~/.config/orbit/theme.toml"

[templates.starship]
input_path = "~/dotfiles/matugen/templates/starship.toml"
output_path = "~/.config/starship.toml"
