# Change prefix.
unbind r
bind r source-file ~/.tmux.conf
set -g prefix C-s

# Status position.
set -g status-position top

# Plugin list.
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'dracula/tmux'
set -g @plugin 'joshmedeski/tmux-nerd-font-window-name'
set -g @plugin 'tmux-plugins/tmux-mode-indicator'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'christoomey/vim-tmux-navigator'

# Dracula configuration.
set -g @dracula-show-powerline true
set -g @dracula-show-flags true
set -g @dracula-show-left-icon session
set -g @dracula-border-contrast true

# Plugins right-side.
set -g @dracula-plugins "cpu-usage ram-usage mode_indicator git time"

# Custom colors.
set -g @dracula-color-main "dark_gray"
set -g @dracula-status-content-colors "white dark_gray"
set -g @dracula-cpu-usage-colors "white dark_gray"
set -g @dracula-ram-usage-colors "white dark_gray"
set -g @dracula-git-colors "white gray"
set -g @dracula-time-colors "white dark_gray"

# Active vs. inactive window.
set -g @dracula-active-pane-color "dark_gray"

# Time format.
set -g @dracula-time-format "%H:%M"
set -g @dracula-show-timezone false

# TPM start.
run '~/.tmux/plugins/tpm/tpm'

# Force status bar dark mode.
set -g status-style "bg=#1e1e1e,fg=#ffffff"
set -g status-left-style "bg=#1e1e1e,fg=#ffffff"
set -g status-right-style "bg=#1e1e1e,fg=#ffffff"
set -g window-status-style "bg=#262626,fg=#808080"
set -g window-status-current-style "bg=#4e4e4e,fg=#ffffff,bold"

set -g status-left "#[bg=#4e4e4e,fg=#ffffff,bold] #S #[bg=#1e1e1e,fg=#4e4e4e]"
set -g window-status-format "#[bg=#262626,fg=#808080] #I #W "
set -g window-status-current-format "#[bg=#4e4e4e,fg=#ffffff,bold] #I #W "
